  version: '3'
    
  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    web:
      build: .      
      command: python CGO_Interview_Session/manage.py runserver 0.0.0.0:9999
      volumes:
        - .:/code
      ports:
        - "9999:9999"
      depends_on:
        - db